{% set name = "sweets" %}
{% set version = "0.3.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/isce-framework/sweets/archive/v{{ version }}.tar.gz
  sha256: 00823ee4682498f50476aabb0f449137a7ba6c7f84f6cad86b8c0f20790f0615

build:
  entry_points:
    - sweets = sweets.cli:main
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - setuptools-scm >=6.2
    - pip >=21.3
  run:
    - python >={{ python_min }}
    - affine
    - aiohttp
    - asf_search
    - botocore
    - burst2safe
    - compass >=0.4.1
    - dask
    - dolphin >=0.3.0
    - fsspec
    - gdal
    - geopandas
    - h5netcdf
    - h5py >=3.6
    - hdf5 !=1.12.2 # https://github.com/SciTools/iris/issues/5187 and https://github.com/pydata/xarray/issues/7549
    - isce3 >=0.24
    - libgdal-netcdf
    - loguru
    - numpy >=1.25
    - opera-utils
    - pandas
    - pydantic >=2.1
    - pyogrio
    - pyproj >=3.2
    - python-dateutil
    - rasterio
    - requests >=2.10
    - rich >=12.0
    - rioxarray
    - s3fs
    - sardem
    - scipy
    - sentineleof
    - shapely >=2.0
    - tqdm
    - tyro
    - xarray
    - zarr >=3

test:
  imports:
    - sweets
    - sweets.core
  commands:
    - sweets --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/isce-framework/sweets
  summary: Workflows for generating surface displacement maps using InSAR
  license: BSD-3-Clause OR Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/isce-framework/sweets

extra:
  recipe-maintainers:
    - scottstanie
